import { useMemo, useState } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell, ScatterChart, Scatter, CartesianGrid, ReferenceLine } from "recharts";
import { solve, buildResult, PRODUCTS, WOVEN, KNIT, TYPE, RM_G, PROFIT, MIN_SKU, LABOR_DAYS, SELL_PRICE, WOVEN_RM_LIMIT, KNIT_RM_LIMIT, NUM_WEAVERS, NUM_KNITTERS, PLANNING_DAYS, WEAVER_DAYS_LIMIT, KNITTER_DAYS_LIMIT, COLORS, SENS_DELTAS, SENS_DATA, RHS_FACTORS, RHS_DATA, SCENARIOS, PARETO, fmt, fmtK, pct, num, TT, KPI, ResBar } from "./data.jsx";

export function UnitEconomicsTab() {
  const opt = useMemo(() => solve(), []);
  const unitData = PRODUCTS.map((p,i) => ({name:p, type:TYPE[p], color:COLORS[i], rm:RM_G[p], labor:LABOR_DAYS[p], profit:PROFIT[p], profitPerGram: PROFIT[p]/RM_G[p], profitPerDay: PROFIT[p]/LABOR_DAYS[p], optUnits:opt.units[p]}));
  const constraintStory = PRODUCTS.map((p,i) => {const isW = WOVEN.includes(p); const rmLimit = isW?WOVEN_RM_LIMIT:KNIT_RM_LIMIT; const labLimit = isW?WEAVER_DAYS_LIMIT:KNITTER_DAYS_LIMIT; const maxByRM = Math.floor(rmLimit/RM_G[p]); const maxByLab = Math.floor(labLimit/LABOR_DAYS[p]); return {product:p, maxByRM, maxByLab, binding: maxByRM<maxByLab?(isW?"Woven RM":"Knit RM"):(isW?"Weaver-Days":"Knitter-Days"), maxAlone: Math.min(maxByRM,maxByLab)};});
  return (<div>
    <div className="bg-gradient-to-r from-cyan-900/20 to-gray-800/40 border border-cyan-800/30 rounded-xl p-5 mb-6"><h3 className="text-base font-bold text-white mb-2">What does one unit of each product actually earn?</h3><p className="text-sm text-gray-400 leading-relaxed">A Shawl earns <span className="text-cyan-400 font-bold">{fmt(PROFIT.Shawl)}</span> — the highest per unit. But it eats <span className="text-amber-400 font-bold">510g</span> of raw material. A Muffler earns only <span className="text-cyan-400 font-bold">{fmt(PROFIT.Muffler)}</span> but uses just <span className="text-emerald-400 font-bold">175g</span>. The optimizer picks products that <em className="text-white font-semibold">squeeze the most profit from limited resources</em>.</p></div>
    <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 mb-6">{unitData.map(d => (<div key={d.name} className="bg-gray-800/50 border border-gray-700/40 rounded-xl p-3 relative overflow-hidden"><div className="absolute top-0 right-0 w-16 h-16 rounded-bl-full opacity-10" style={{backgroundColor:d.color}}/><div className="flex items-center gap-2 mb-2"><div className="w-2.5 h-2.5 rounded-full" style={{backgroundColor:d.color}}/><span className="text-sm font-bold text-gray-200">{d.name}</span><span className="text-[9px] px-1.5 py-0.5 rounded bg-gray-700 text-gray-400 font-semibold">{d.type}</span></div><div className="text-xl font-black text-white mb-0.5">{fmt(d.profit)}</div><div className="text-[10px] text-gray-500 uppercase tracking-wider font-bold mb-3">Profit per unit</div><div className="space-y-1.5 text-xs"><div className="flex justify-between"><span className="text-gray-500">Raw material</span><span className="text-gray-300 font-semibold">{d.rm}g</span></div><div className="flex justify-between"><span className="text-gray-500">Labor time</span><span className="text-gray-300 font-semibold">{d.labor.toFixed(2)} days</span></div><div className="flex justify-between"><span className="text-gray-500">₹ per gram</span><span className="text-cyan-400 font-bold">{d.profitPerGram.toFixed(2)}</span></div><div className="flex justify-between"><span className="text-gray-500">₹ per labor-day</span><span className="text-amber-400 font-bold">{fmt(d.profitPerDay,0)}</span></div><div className="border-t border-gray-700 pt-1.5 flex justify-between"><span className="text-gray-500">Optimizer picks</span><span className="text-white font-black">{d.optUnits} units</span></div></div></div>))}</div>
    <div className="grid md:grid-cols-2 gap-4 mb-6">
      <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><h3 className="text-sm font-bold text-gray-200 mb-1">Material Efficiency: ₹ profit per gram</h3><p className="text-[10px] text-gray-500 mb-3">Who extracts the most value from scarce raw material?</p><ResponsiveContainer width="100%" height={200}><BarChart data={[...unitData].sort((a,b)=>b.profitPerGram-a.profitPerGram).map(d=>({name:d.name,value:+d.profitPerGram.toFixed(2),fill:d.color}))} layout="vertical" margin={{left:5,right:30}}><XAxis type="number" tick={{fill:'#9CA3AF',fontSize:10}}/><YAxis type="category" dataKey="name" tick={{fill:'#9CA3AF',fontSize:11}} width={65}/><Tooltip content={<TT formatter={v=>`₹${v}/g`}/>}/><Bar dataKey="value" name="₹/gram" radius={[0,4,4,0]}>{[...unitData].sort((a,b)=>b.profitPerGram-a.profitPerGram).map((d,i)=><Cell key={i} fill={d.color}/>)}</Bar></BarChart></ResponsiveContainer></div>
      <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><h3 className="text-sm font-bold text-gray-200 mb-1">Labor Efficiency: ₹ profit per artisan-day</h3><p className="text-[10px] text-gray-500 mb-3">Who generates the most per day of work?</p><ResponsiveContainer width="100%" height={200}><BarChart data={[...unitData].sort((a,b)=>b.profitPerDay-a.profitPerDay).map(d=>({name:d.name,value:Math.round(d.profitPerDay),fill:d.color}))} layout="vertical" margin={{left:5,right:30}}><XAxis type="number" tick={{fill:'#9CA3AF',fontSize:10}} tickFormatter={v=>`₹${(v/1000).toFixed(0)}K`}/><YAxis type="category" dataKey="name" tick={{fill:'#9CA3AF',fontSize:11}} width={65}/><Tooltip content={<TT formatter={v=>fmt(v)+'/day'}/>}/><Bar dataKey="value" name="₹/day" radius={[0,4,4,0]}>{[...unitData].sort((a,b)=>b.profitPerDay-a.profitPerDay).map((d,i)=><Cell key={i} fill={d.color}/>)}</Bar></BarChart></ResponsiveContainer></div>
    </div>
    <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><h3 className="text-sm font-bold text-gray-200 mb-1">How Do the 4 Constraints Limit Each Product?</h3><p className="text-[10px] text-gray-500 mb-3">If you could <em>only</em> make one product, how many before hitting each wall?</p><table className="w-full text-xs"><thead><tr className="border-b border-gray-700 text-gray-400"><th className="text-left py-2">Product</th><th className="text-right">Max by RM</th><th className="text-right">Max by Labor</th><th className="text-right">Which binds first?</th><th className="text-right">Solo max</th><th className="text-right">Optimizer</th></tr></thead><tbody>{constraintStory.map((c,i) => (<tr key={c.product} className="border-b border-gray-800/60"><td className="py-2 font-semibold" style={{color:COLORS[i]}}>{c.product}</td><td className="text-right text-gray-400">{c.maxByRM}</td><td className="text-right text-gray-400">{c.maxByLab}</td><td className={`text-right font-bold ${c.binding.includes("RM")?"text-amber-400":"text-red-400"}`}>{c.binding}</td><td className="text-right text-gray-300 font-semibold">{c.maxAlone}</td><td className="text-right text-white font-black">{opt.units[c.product]}</td></tr>))}</tbody></table><div className="mt-3 p-3 bg-gray-900/60 rounded-lg border border-cyan-900/30 text-xs text-gray-400"><span className="text-cyan-400 font-bold">The key insight:</span> The optimizer finds the <em>combination</em> that maximizes total profit across all products sharing fixed resource pools.</div></div>
  </div>);
}

export function AllocationTab() {
  const opt = useMemo(() => solve(), []);
  const [userUnits, setUserUnits] = useState(() => {const u = {}; PRODUCTS.forEach(p => u[p] = MIN_SKU[p]); return u;});
  const userResult = useMemo(() => buildResult(userUnits), [userUnits]);
  const profitGap = opt.profit - userResult.profit;
  const gapPct = (profitGap / opt.profit * 100);
  const setUnit = (p, v) => setUserUnits(prev => ({...prev, [p]: Math.max(0, Math.round(v))}));
  return (<div>
    <div className="bg-gradient-to-r from-amber-900/20 to-gray-800/40 border border-amber-800/30 rounded-xl p-5 mb-6"><h3 className="text-base font-bold text-white mb-2">Can you beat the optimizer?</h3><p className="text-sm text-gray-400">Pick your own product quantities. Resources are <span className="text-red-400 font-bold">fixed</span>: Woven RM capped at {num(WOVEN_RM_LIMIT)}g, Knit RM at {num(KNIT_RM_LIMIT)}g, {NUM_WEAVERS} weavers and {NUM_KNITTERS} knitters for {PLANNING_DAYS} days.</p></div>
    <div className="grid lg:grid-cols-3 gap-4 mb-6">
      <div className="lg:col-span-2 bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><div className="flex items-center justify-between mb-3"><h3 className="text-sm font-bold text-gray-200">Your Product Mix</h3><div className="flex gap-2"><button onClick={()=>{const u={};PRODUCTS.forEach(p=>u[p]=MIN_SKU[p]);setUserUnits(u);}} className="text-[10px] px-2.5 py-1 border border-gray-600 text-gray-400 rounded-lg hover:border-cyan-600 hover:text-cyan-400 transition-colors">Reset Min SKU</button><button onClick={()=>{const u={};PRODUCTS.forEach(p=>u[p]=opt.units[p]);setUserUnits(u);}} className="text-[10px] px-2.5 py-1 border border-cyan-700 text-cyan-400 rounded-lg hover:bg-cyan-900/30 transition-colors">Load Optimal</button></div></div><div className="grid grid-cols-2 gap-x-6"><div><div className="text-[9px] uppercase tracking-widest text-gray-500 font-bold mb-2">🧶 Woven Products</div>{WOVEN.map(p=>{const gi=PRODUCTS.indexOf(p);return(<div key={p} className="flex items-center gap-2 mb-2.5"><span className="text-xs w-12 font-bold" style={{color:COLORS[gi]}}>{p}</span><button onClick={()=>setUnit(p,userUnits[p]-1)} className="w-7 h-7 rounded bg-gray-700 text-gray-300 hover:bg-gray-600 flex items-center justify-center font-bold">−</button><input type="number" value={userUnits[p]} onChange={e=>setUnit(p,parseInt(e.target.value)||0)} className="w-16 text-center bg-gray-900 border border-gray-600 rounded text-sm text-white py-1 font-mono focus:border-cyan-500 focus:outline-none"/><button onClick={()=>setUnit(p,userUnits[p]+1)} className="w-7 h-7 rounded bg-gray-700 text-gray-300 hover:bg-gray-600 flex items-center justify-center font-bold">+</button><span className="text-[10px] text-gray-600 ml-1">min {MIN_SKU[p]}</span></div>);})}</div><div><div className="text-[9px] uppercase tracking-widest text-gray-500 font-bold mb-2">🧵 Knit Products</div>{KNIT.map(p=>{const gi=PRODUCTS.indexOf(p);return(<div key={p} className="flex items-center gap-2 mb-2.5"><span className="text-xs w-16 font-bold" style={{color:COLORS[gi]}}>{p}</span><button onClick={()=>setUnit(p,userUnits[p]-1)} className="w-7 h-7 rounded bg-gray-700 text-gray-300 hover:bg-gray-600 flex items-center justify-center font-bold">−</button><input type="number" value={userUnits[p]} onChange={e=>setUnit(p,parseInt(e.target.value)||0)} className="w-16 text-center bg-gray-900 border border-gray-600 rounded text-sm text-white py-1 font-mono focus:border-cyan-500 focus:outline-none"/><button onClick={()=>setUnit(p,userUnits[p]+1)} className="w-7 h-7 rounded bg-gray-700 text-gray-300 hover:bg-gray-600 flex items-center justify-center font-bold">+</button><span className="text-[10px] text-gray-600 ml-1">min {MIN_SKU[p]}</span></div>);})}</div></div></div>
      <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 flex flex-col"><div className="text-center mb-3"><div className="text-[10px] uppercase tracking-widest text-gray-500 font-bold mb-1">Your Profit</div><div className={`text-3xl font-black ${userResult.feasible?'text-white':'text-red-400'}`}>{fmt(userResult.profit)}</div>{!userResult.feasible && <div className="text-xs text-red-400 font-bold mt-1 animate-pulse">⛔ OVER RESOURCE LIMITS</div>}</div><div className={`text-center p-3 rounded-lg mb-3 ${profitGap>100?'bg-red-900/20 border border-red-800/30':'bg-emerald-900/20 border border-emerald-800/30'}`}><div className="text-[10px] uppercase tracking-widest text-gray-500 font-bold mb-1">vs. Optimizer ({fmt(opt.profit)})</div>{profitGap > 100 ? (<div className="text-red-400 font-bold text-sm">Leaving {fmt(profitGap)} on the table ({gapPct.toFixed(1)}%)</div>) : (<div className="text-emerald-400 font-bold text-sm">You matched the optimizer! 🎯</div>)}</div><div className="text-center p-2 bg-gray-900/40 rounded-lg border border-gray-700/40 text-[10px] text-gray-500">Optimal: {PRODUCTS.map(p=>`${p.substring(0,3)}=${opt.units[p]}`).join(', ')}</div><div className="flex-1"/><div className="text-[10px] text-gray-600 text-center mt-2">Units: {userResult.totalUnits} · Rev: {fmt(userResult.revenue)}</div></div>
    </div>
    <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 mb-6"><h3 className="text-sm font-bold text-gray-200 mb-3">Resource Consumption — Hard Caps</h3><div className="grid md:grid-cols-2 gap-x-8"><div><div className="text-[9px] uppercase tracking-widest text-gray-500 font-bold mb-2">Woven</div><ResBar label="Woven Raw Material" used={userResult.wovenRM.used} limit={WOVEN_RM_LIMIT} unit="g"/><ResBar label="Weaver-Days" used={userResult.weaverDays.used} limit={WEAVER_DAYS_LIMIT}/></div><div><div className="text-[9px] uppercase tracking-widest text-gray-500 font-bold mb-2">Knit</div><ResBar label="Knit Raw Material" used={userResult.knitRM.used} limit={KNIT_RM_LIMIT} unit="g"/><ResBar label="Knitter-Days" used={userResult.knitterDays.used} limit={KNITTER_DAYS_LIMIT}/></div></div></div>
    <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><h3 className="text-sm font-bold text-gray-200 mb-3">Profit by Product: Yours vs Optimal</h3><ResponsiveContainer width="100%" height={220}><BarChart data={PRODUCTS.map(p=>({name:p,yours:PROFIT[p]*(userUnits[p]||0),optimal:PROFIT[p]*opt.units[p]}))} margin={{top:5,right:5,bottom:5,left:5}}><CartesianGrid strokeDasharray="3 3" stroke="#374151"/><XAxis dataKey="name" tick={{fill:'#9CA3AF',fontSize:11}}/><YAxis tick={{fill:'#9CA3AF',fontSize:10}} tickFormatter={v=>fmtK(v)}/><Tooltip content={<TT formatter={v=>fmt(v)}/>}/><Legend iconSize={8} wrapperStyle={{fontSize:11}}/><Bar dataKey="yours" name="Your Profit" fill="#6B7280" radius={[3,3,0,0]}/><Bar dataKey="optimal" name="Optimal" fill="#06B6D4" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>
  </div>);
}

export function BaselineTab() {
  const sol = useMemo(() => solve(), []);
  const mixData = PRODUCTS.map((p,i)=>({name:p,units:sol.units[p],fill:COLORS[i]}));
  const pieData = PRODUCTS.map((p,i)=>({name:p,value:Math.round(PROFIT[p]*sol.units[p]),fill:COLORS[i]}));
  return (<div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6"><KPI label="Total Profit" value={fmt(sol.profit)} sub="30-day window"/><KPI label="Revenue" value={fmt(sol.revenue)} color="text-amber-400"/><KPI label="Total Units" value={num(sol.totalUnits)} color="text-emerald-400"/><KPI label="RM Used" value={`${num(PRODUCTS.reduce((s,p)=>s+RM_G[p]*sol.units[p],0))}g`} color="text-purple-400"/></div>
    <div className="grid md:grid-cols-2 gap-4 mb-6"><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><h3 className="text-sm font-bold text-gray-200 mb-3">Optimal Product Mix</h3><ResponsiveContainer width="100%" height={220}><BarChart data={mixData}><CartesianGrid strokeDasharray="3 3" stroke="#374151"/><XAxis dataKey="name" tick={{fill:'#9CA3AF',fontSize:11}}/><YAxis tick={{fill:'#9CA3AF',fontSize:11}}/><Tooltip content={<TT/>}/><Bar dataKey="units" radius={[4,4,0,0]}>{mixData.map((d,i)=><Cell key={i} fill={d.fill}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><h3 className="text-sm font-bold text-gray-200 mb-3">Profit Contribution</h3><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={pieData} cx="50%" cy="50%" innerRadius={50} outerRadius={85} paddingAngle={2} dataKey="value">{pieData.map((e,i)=><Cell key={i} fill={e.fill}/>)}</Pie><Tooltip content={<TT formatter={v=>fmt(v)}/>}/><Legend iconSize={8} wrapperStyle={{fontSize:11}}/></PieChart></ResponsiveContainer></div></div>
    <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 mb-6"><h3 className="text-sm font-bold text-gray-200 mb-3">Resource Utilization</h3><div className="grid md:grid-cols-2 gap-x-8"><div><div className="text-[9px] uppercase tracking-widest text-gray-500 font-bold mb-2">Woven</div><ResBar label="Raw Material" used={sol.wovenRM.used} limit={WOVEN_RM_LIMIT} unit="g"/><ResBar label="Weaver-Days" used={sol.weaverDays.used} limit={WEAVER_DAYS_LIMIT}/></div><div><div className="text-[9px] uppercase tracking-widest text-gray-500 font-bold mb-2">Knit</div><ResBar label="Raw Material" used={sol.knitRM.used} limit={KNIT_RM_LIMIT} unit="g"/><ResBar label="Knitter-Days" used={sol.knitterDays.used} limit={KNITTER_DAYS_LIMIT}/></div></div><div className="mt-4 p-3 bg-gray-900/60 rounded-lg border border-cyan-900/30"><div className="text-xs font-bold text-cyan-400 mb-1">⚡ Binding Constraints</div><p className="text-xs text-gray-400">Knitter capacity at <span className="text-red-400 font-bold">99.9%</span> — the true bottleneck. Woven RM at <span className="text-red-400 font-bold">99.6%</span>. Weavers only <span className="text-emerald-400 font-bold">19.9%</span> utilized.</p></div></div>
    <div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 overflow-x-auto"><h3 className="text-sm font-bold text-gray-200 mb-3">Full Detail</h3><table className="w-full text-xs"><thead><tr className="border-b border-gray-700 text-gray-400"><th className="text-left py-2">Product</th><th className="text-right">Units</th><th className="text-right">RM (g)</th><th className="text-right">Profit/Unit</th><th className="text-right">₹/g</th><th className="text-right">₹/day</th><th className="text-right">Total Profit</th></tr></thead><tbody>{PRODUCTS.map((p,i)=>(<tr key={p} className="border-b border-gray-800/60"><td className="py-2 font-semibold" style={{color:COLORS[i]}}>{p} <span className="text-gray-600">({TYPE[p]})</span></td><td className="text-right font-bold text-white">{sol.units[p]}</td><td className="text-right text-gray-400">{RM_G[p]}</td><td className="text-right text-gray-300">{fmt(PROFIT[p])}</td><td className="text-right text-cyan-400">{(PROFIT[p]/RM_G[p]).toFixed(2)}</td><td className="text-right text-amber-400">{fmt(PROFIT[p]/LABOR_DAYS[p],0)}</td><td className="text-right font-bold text-white">{fmt(PROFIT[p]*sol.units[p])}</td></tr>))}<tr className="border-t-2 border-gray-600 font-bold text-white"><td className="py-2">TOTAL</td><td className="text-right">{sol.totalUnits}</td><td colSpan={4}></td><td className="text-right text-cyan-400">{fmt(sol.profit)}</td></tr></tbody></table></div>
  </div>);
}

export function SensitivityTab() {
  const d = SENS_DELTAS.map((delta,i)=>{const r={delta:`${delta>0?'+':''}${delta}%`};PRODUCTS.forEach(p=>{r[p]=SENS_DATA[p][i]});return r;});
  return (<div><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 mb-6"><h3 className="text-sm font-bold text-gray-200 mb-1">Profit Sensitivity to Unit Margins</h3><p className="text-xs text-gray-500 mb-4">Each line: what happens to total profit if that product's profit/unit changes ±50%.</p><ResponsiveContainer width="100%" height={340}><LineChart data={d}><CartesianGrid strokeDasharray="3 3" stroke="#374151"/><XAxis dataKey="delta" tick={{fill:'#9CA3AF',fontSize:10}}/><YAxis tick={{fill:'#9CA3AF',fontSize:10}} tickFormatter={v=>fmtK(v)} domain={['auto','auto']}/><Tooltip content={<TT formatter={v=>fmt(v)}/>}/><ReferenceLine y={314692.20} stroke="#6B7280" strokeDasharray="5 5"/>{PRODUCTS.map((p,i)=><Line key={p} type="monotone" dataKey={p} stroke={COLORS[i]} strokeWidth={2} dot={{r:3}}/>)}<Legend iconSize={8} wrapperStyle={{fontSize:11}}/></LineChart></ResponsiveContainer></div><div className="bg-gray-800/40 border border-cyan-900/30 rounded-xl p-4 text-xs text-gray-400 space-y-2"><p><span className="text-white font-semibold">Steep = sensitive.</span> Sweater and Muffler have the largest upside slopes.</p><p><span className="text-white font-semibold">Flat = irrelevant.</span> Cap &amp; Gloves at minimum SKU — near-zero impact.</p></div></div>);
}

export function RHSTab() {
  const d = RHS_FACTORS.map((f,i)=>{const r={factor:`×${f.toFixed(2)}`};Object.keys(RHS_DATA).forEach(k=>{r[k]=RHS_DATA[k][i]});return r;});
  const c = ["#2E86AB","#A23B72","#44BBA4","#E94F37"];
  return (<div><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 mb-6"><h3 className="text-sm font-bold text-gray-200 mb-1">What If Resource Limits Changed? (Hypothetical)</h3><p className="text-xs text-gray-500 mb-4">Scales each limit 50%–200% individually.</p><ResponsiveContainer width="100%" height={340}><LineChart data={d}><CartesianGrid strokeDasharray="3 3" stroke="#374151"/><XAxis dataKey="factor" tick={{fill:'#9CA3AF',fontSize:10}}/><YAxis tick={{fill:'#9CA3AF',fontSize:10}} tickFormatter={v=>fmtK(v)} domain={['auto','auto']}/><Tooltip content={<TT formatter={v=>fmt(v)}/>}/><ReferenceLine x="×1.00" stroke="#6B7280" strokeDasharray="5 5"/>{Object.keys(RHS_DATA).map((r,i)=><Line key={r} type="monotone" dataKey={r} stroke={c[i]} strokeWidth={2.5} dot={{r:4}}/>)}<Legend iconSize={8} wrapperStyle={{fontSize:11}}/></LineChart></ResponsiveContainer></div><div className="grid md:grid-cols-2 gap-4"><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 text-xs text-gray-400 space-y-2"><p><span className="text-cyan-400 font-bold">Woven RM (steepest):</span> Every +1kg → ~₹13,940 profit.</p><p><span className="text-red-400 font-bold">Knitter-Days:</span> Valuable up to ×1.25, then flat.</p><p><span className="text-emerald-400 font-bold">Weaver-Days:</span> Completely flat. Zero marginal value.</p></div><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4"><table className="w-full text-xs"><thead><tr className="border-b border-gray-700 text-gray-400"><th className="text-left py-1.5">Resource</th><th className="text-right">Shadow Value</th><th className="text-right">Status</th></tr></thead><tbody>{[{r:"Woven RM",v:"≈₹13.94/g",s:"Binding",c:"text-red-400"},{r:"Knit RM",v:"₹0/g",s:"Surplus",c:"text-emerald-400"},{r:"Weaver-Days",v:"₹0/day",s:"Surplus",c:"text-emerald-400"},{r:"Knitter-Days",v:"≈₹538/day",s:"Binding",c:"text-red-400"}].map(x=>(<tr key={x.r} className="border-b border-gray-800/60"><td className="py-1.5 text-gray-300 font-semibold">{x.r}</td><td className="text-right text-cyan-400 font-semibold">{x.v}</td><td className={`text-right font-bold ${x.c}`}>{x.s}</td></tr>))}</tbody></table></div></div></div>);
}

export function ScenarioTab() {
  const cd = SCENARIOS.map(s=>({name:s.name.length>22?s.name.substring(0,22)+'…':s.name,profit:s.profit,fill:s.name==="Base Case"?"#2E86AB":s.profit>314692.20?"#44BBA4":"#C73E1D"}));
  const bu = SCENARIOS[0].units;
  return (<div><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 mb-6"><h3 className="text-sm font-bold text-gray-200 mb-3">Scenario Profit Comparison</h3><ResponsiveContainer width="100%" height={260}><BarChart data={cd} layout="vertical" margin={{right:30,left:5}}><CartesianGrid strokeDasharray="3 3" stroke="#374151"/><XAxis type="number" tick={{fill:'#9CA3AF',fontSize:10}} tickFormatter={v=>fmtK(v)}/><YAxis type="category" dataKey="name" tick={{fill:'#9CA3AF',fontSize:10}} width={155}/><Tooltip content={<TT formatter={v=>fmt(v,2)}/>}/><ReferenceLine x={314692.20} stroke="#6B7280" strokeDasharray="5 5"/><Bar dataKey="profit" name="Profit" radius={[0,4,4,0]}>{cd.map((e,i)=><Cell key={i} fill={e.fill}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 mb-6 overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-700 text-gray-400"><th className="text-left py-2">Scenario</th>{PRODUCTS.map(p=><th key={p} className="text-right px-1.5">{p.substring(0,3)}</th>)}<th className="text-right px-2">Profit</th><th className="text-right px-2">Δ</th></tr></thead><tbody>{SCENARIOS.map(s=>{const d=s.profit-314692.20;return(<tr key={s.name} className="border-b border-gray-800/60"><td className="py-2 text-gray-300 font-semibold whitespace-nowrap">{s.name}</td>{PRODUCTS.map(p=><td key={p} className={`text-right px-1.5 font-mono ${s.units[p]!==bu[p]?'text-amber-400 font-bold':'text-gray-400'}`}>{s.units[p]}</td>)}<td className="text-right px-2 font-bold text-white">{fmt(s.profit)}</td><td className={`text-right px-2 font-bold ${d>0?'text-emerald-400':d<0?'text-red-400':'text-gray-500'}`}>{d===0?'—':`${d>0?'+':''}${fmt(d)}`}</td></tr>);})}</tbody></table></div><div className="bg-gray-800/40 border border-cyan-900/30 rounded-xl p-4 text-xs text-gray-400 grid md:grid-cols-2 gap-4"><div><p className="mb-2"><span className="text-amber-400 font-bold">+2 Weavers = zero impact.</span> Already surplus.</p><p><span className="text-emerald-400 font-bold">+2 Knitters = +₹27,781.</span> All goes to Mufflers.</p></div><div><p className="mb-2"><span className="text-emerald-400 font-bold">Best: RM+25% &amp; Labour = +₹62,705.</span></p><p><span className="text-red-400 font-bold">RM−25% = −₹55,212.</span> Devastating.</p></div></div></div>);
}

export function ParetoTab() {
  return (<div><div className="bg-gray-800/40 border border-gray-700/40 rounded-xl p-4 mb-6"><h3 className="text-sm font-bold text-gray-200 mb-1">Pareto: Profit vs. Raw Material Conservation</h3><p className="text-xs text-gray-500 mb-4">max α·Profit − (1−α)·TotalRM. α=1 = pure profit. α=0 = pure conservation.</p><ResponsiveContainer width="100%" height={300}><ScatterChart margin={{top:10,right:20,bottom:10,left:10}}><CartesianGrid strokeDasharray="3 3" stroke="#374151"/><XAxis dataKey="rm" type="number" tick={{fill:'#9CA3AF',fontSize:10}} label={{value:'RM Used (g)',position:'insideBottom',offset:-2,style:{fill:'#6B7280',fontSize:10}}}/><YAxis dataKey="profit" tick={{fill:'#9CA3AF',fontSize:10}} tickFormatter={v=>fmtK(v)}/><Tooltip content={({active,payload})=>{if(!active||!payload?.length)return null;const d=payload[0]?.payload;return(<div className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-xs shadow-xl"><p className="text-gray-300">α={d?.alpha?.toFixed(2)}</p><p className="text-cyan-400">Profit: {fmt(d?.profit)}</p><p className="text-amber-400">RM: {num(d?.rm)}g</p></div>);}}/><Scatter data={PARETO} fill="#06B6D4" stroke="#0891B2" strokeWidth={1}/></ScatterChart></ResponsiveContainer></div><div className="bg-gray-800/40 border border-cyan-900/30 rounded-xl p-4 text-xs text-gray-400"><p className="mb-2"><span className="text-cyan-400 font-bold">Binary frontier:</span> Either min-SKU only (7,150g, ₹62K) or full production (34,430g, ₹315K).</p><p>The most profitable products are also the most material-efficient, so profit maximization and resource conservation align here.</p></div></div>);
}
